### ISSUE TITLE
[Bug] Potential memory leaks when redrawing snippets 

### ISSUE THREAD

**Issue by mskocik** [matronator/axette#12]
When updating snippets, which contains ajaxified links, their click handlers are not removed. Therefore resulting in memory leaks. Although small, but still present.

These links should have event listeners removed before snippet's HTML being rewritten.

**Comment by matronator** [comment]
Thank you, I completely missed that. I will take a look at it as soon as I can.

**Comment by matronator** [comment]
Fix in the latest commit c0b326fa6b0c04da8c564bb3e30ab79e6e387d77.
