### ISSUE TITLE
How to use with cdn?

### ISSUE THREAD

**Issue by eydun** [matronator/axette#75]
I have added to @layout.latte

```javascript
    <script src="https://unpkg.com/axette@latest/dist/axette.iife.js"></script>
    <script>
        import { Axette } from "axette";
        const axette = new Axette();
    </script>
```
When opening page, I get the error:
```error
Uncaught SyntaxError: import declarations may only appear at top level of a module
```
Please advice.

**Comment by matronator** [comment]
Hi! There are few ways in which you can use the library with a CDN.

#### Using the `iife` version

You are loading the `iife` version of the library, meaning you don't need to import anything as the `axette` object is loaded as a global variable and available on the `window` object.

So you'd just do this:

```html
<script src="https://unpkg.com/axette@latest/dist/axette.iife.js"></script>
<script>
    console.log(axette);
</script>
```

#### Using ES modules

But if you want to use ES6 imports, first you have to add `type="module"` to your script tags. Then you need to load a different version of the library, the `.mjs` one. So to putting it all together, it'll look like this:

```html
<script src="https://unpkg.com/axette@latest/dist/axette.mjs" type="module"></script>
<script type="module">
	import { Axette } from "axette";
    const axette = new Axette();
</script>
```

Hope that helps, please let me know if I can close the issue, or if you have any other questions))

**Comment by matronator** [comment]
> Thank you for the great explanation!
> 
> When I use the
> 
> ```js
> <script src="https://unpkg.com/axette@latest/dist/axette.mjs" type="module"></script>
> <script type="module">
> 	import { Axette } from "axette";
>     const axette = new Axette();
> </script>
> ```
> 
> I get the error: `Uncaught TypeError: The specifier “axette” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.`

Sorry, I was wrong about how you should use `import` with a CDN. Apparently, you don't need two `<script>` tags, you just import directly from the CDN. So it would be like this:

```html
<script type="module">
	import { Axette } from "https://unpkg.com/axette@latest/dist/axette.mjs";
    const axette = new Axette();
</script>
```
